maximum_name_email: 50
minimum: 6
maximum_name: 60
maximum_address: 80
min_range_phone: 10
max_range_phone: 11
per_page: 10
maximum_info: 500
collect_from: 1
collect_to: 99
add_cartitem: 1
total: 0
reject_order: 3
limit_info: 70
separator_info: " "
rating: 0
average_total: 0
maximum_comment: 500
del_success_cmt: 1
del_fail_cmt: 2
del_not_found_cmt: 3
average_total: 0
width_comment_face: 300
num_post: 4
