maximum_name_email: 50
minimum: 6
maximum_name: 60
maximum_address: 80
min_range_phone: 10
max_range_phone: 11
per_page: 10
maximum_info: 500
collect_from: 1
collect_to: 99
add_cartitem: 1
total: 0
reject_order: 3
limit_info: 70
separator_info: " "
rating: 0
average_total: 0
maximum_comment: 500
del_success_cmt: 1
del_fail_cmt: 2
del_not_found_cmt: 3
average_total: 0
width_comment_face: 300
num_post: 4
max_name_suggest: 300
hot_active: 1
init_count: 0
increase_count: 1
is_active: 1
is_first: 1
not_active: 0
is_last: 3
hot_products: 6
one_month_ago: 1
two_month_ago: 2
status_true: true
status_false: false
format_month: "%B"
background_red: "rgba(255, 99, 132, 0.2)"
background_purple: "rgba(153, 102, 255, 0.2)"
background_blue: "rgba(54, 162, 235, 0.2)"
border_red: "rgba(255,99,132,1)"
border_purple: "rgba(153, 102, 255, 1)"
border_blue: "rgba(54, 162, 235, 1)"
